extends "res://tests/playback_v2.gd"

var thunder_count:=0

func toggle(name:String) -> void:
	var control:CheckButton=game.ui.popup.get_node(name)
	var point:=control.get_global_rect().get_center()
	button(point,true);button(point,false)
	await pause(.16)

func no_visuals() -> bool:
	return not game.ui.stage.visible and not game.in_cinema and not is_instance_valid(game.charge_preview) and not is_instance_valid(game.bow_preview) and not game.fx.get_children().any(func(n:Node):return n is Node3D and not n.is_queued_for_deletion()) and not game.stone_root.find_children("*","GPUParticles3D",true,false).any(func(n:Node):return not n.is_queued_for_deletion())

func run(target) -> void:
	game=target
	var version:String=ProjectSettings.get_setting("application/config/version")
	output=ProjectSettings.globalize_path("res://verification/v"+version)
	game.apply_settings(true,true,true,true,true)
	game.fx.thunder_struck.connect(func():thunder_count+=1)
	game.ui.show_help();await pause(.12)
	check(game.ui.popup.has_node("EffectsToggle") and game.ui.popup.has_node("SkillsToggle"),"settings exposes both independent switches")
	await capture("settings-on")
	await toggle("EffectsToggle")
	check(not game.ui.effects_on and game.ui.skills_on and not game.rules.effects_enabled and game.rules.skills_enabled,"actual effects control changes visuals only")
	await toggle("SkillsToggle")
	check(not game.ui.skills_on and not game.rules.can_charge(),"actual skill control disables hidden moves")
	await capture("settings-off")
	var preference_path:=output+"/settings-fixture.cfg"
	game._save_settings(preference_path)
	game.apply_settings(false,false,false,true,true)
	game._load_settings(preference_path)
	check(not game.ui.effects_on and not game.ui.skills_on and game.ui.sound_on and game.ui.music_on and game.ui.high_quality,"saved switches restore alongside independent audio and quality preferences")
	game.ui.close_modal()
	await fixture(2,1)
	var at:=pos(Vector2i(7,7))
	button(at,true);await pause(2.15)
	check(not game.charge_ready and not is_instance_valid(game.charge_preview),"long press cannot charge when skills are disabled")
	button(at,false);await pause(.4)
	check(game.rules.move_count==1 and game.rules.active() and game.rules.board.count(1)==1 and no_visuals(),"both off gives an ordinary move without a cinematic")
	check(thunder_count==0,"effects off suppresses placement lightning")
	# Enable visuals with skills still disabled; existing first-player stones regain their aura.
	game.ui.show_help();await pause(.08);await toggle("EffectsToggle");game.ui.close_modal()
	check(game.rules.has_effects(1) and not game.rules.can_charge() and game.stones[Vector2i(7,7)].has_meta("aura"),"enabling visuals restores the first player's existing stone aura only")
	await click(Vector2i(0,0));await click(Vector2i(8,7));await idle()
	check(thunder_count==1,"third-round lightning remains available with skills off")
	game.ui.show_help();await pause(.08);await toggle("EffectsToggle")
	check(no_visuals(),"turning off visuals removes existing auras and residual lightning")
	await toggle("SkillsToggle");game.ui.close_modal()
	check(not game.ui.effects_on and game.ui.skills_on,"skills can remain enabled while visuals are off")
	# Every skill keeps its board result while skipping the entire cinematic.
	await fixture(2,1)
	seed_board([[7,5],[7,6],[6,6]],1)
	await click(Vector2i(7,7));await click(Vector2i(0,0))
	var start:=pos(Vector2i(6,6))
	var pull:Vector2=game.scenery.camera.unproject_position(game.world(Vector2i(6,6))+Vector3(-.95,0,0))
	button(start,true);motion(pull);await pause(.16)
	check(game.direction==Vector2i.RIGHT and no_visuals(),"bow drag remains usable without preview VFX")
	button(pull,false);await idle()
	check(game.rules.finish_kind=="bow" and not game.stones.has(Vector2i(6,6)) and game.stones.has(Vector2i(14,6)) and no_visuals(),"plain bow removes its anchor and fills the whole ray")
	await fixture(3,2)
	seed_board([[7,7],[8,7],[7,8]],2)
	await click(Vector2i(8,8));await idle()
	check(game.rules.board.count(2)==25 and game.stones.size()==25 and game.rules.finish_kind=="moon" and no_visuals(),"plain moon resolves all 25 visible white stones")
	await fixture(2,1)
	at=pos(Vector2i(7,7));button(at,true);await pause(2.15)
	check(game.charge_ready and no_visuals(),"silent visual charge preserves the long-press gesture")
	button(at,false);await idle()
	check(game.rules.board.count(1)==225 and game.stones.size()==225 and game.rules.wins==[1,0] and no_visuals(),"plain cosmos resolves once without flash, shake or particles")
	# Closing the settings popup cancels an in-progress gesture when skills are disabled.
	game.apply_settings(true,true,true,true,true)
	await fixture(0,1)
	at=pos(Vector2i(7,7));button(at,true);await pause(.55)
	check(is_instance_valid(game.charge_preview),"enabled visuals still show a charge")
	game.ui.show_help();await pause(.08);await toggle("SkillsToggle")
	button(at,false);game.ui.close_modal();await pause(.15)
	check(not game.rules.can_charge() and game.rules.move_count==0 and not game.charge_ready and not is_instance_valid(game.charge_preview),"turning skills off cancels held input without accidental placement")
	await fixture(1,2)
	seed_board([[7,7],[8,7],[7,8]],2)
	await click(Vector2i(8,8));await idle()
	check(game.rules.board.count(2)==4 and game.rules.turn==1 and game.rules.active(),"a disabled white ring completes an ordinary turn")
	# Old settings have both new features enabled by default.
	var legacy:=ConfigFile.new()
	legacy.set_value("audio","sound",false);legacy.set_value("audio","music",true)
	legacy.set_value("graphics","full",false)
	legacy.save(output+"/legacy-settings.cfg")
	game._load_settings(output+"/legacy-settings.cfg")
	check(game.ui.effects_on and game.ui.skills_on and not game.ui.sound_on and game.ui.music_on and not game.ui.high_quality,"old preferences retain their values and default both new switches on")
	await fixture(1,1)
	await click(Vector2i(7,7))
	check(not game.stones[Vector2i(7,7)].has_meta("aura"),"switches do not transfer advantage to the second player after color swap")
	game.ui.show_help();await pause(.15)
	var visible_words:=""
	for label_node in game.ui.popup.find_children("*","Label",true,false):visible_words+=label_node.text
	check(not ["三连","四子","长按","拉弓","5×5"].any(func(word:String):return visible_words.contains(word)),"settings does not disclose skill triggers")
	FileAccess.open(output+"/settings-playback.json",FileAccess.WRITE).store_string(JSON.stringify({"checks":checks,"failures":failures,"thunder_count":thunder_count},"  "))
	print("SETTINGS CHECK: ",checks," checks; ",failures.size()," failures")
	await game._shutdown_audio()
	get_tree().quit(0 if failures.is_empty() else 1)
